import { get, post, put, del } from './request'

export const getDashboard = () => get('/api/admin/overview')
export const getRevenueStats = (params) => get('/api/admin/stats/revenue', params)
export const getUserStats = (params) => get('/api/admin/stats/users', params)
export const getRequestStats = (params) => get('/api/admin/stats/requests', params)
export const listUsers = (params) => get('/api/admin/users', params)
export const updateUserStatus = (id, data) => put(`/api/admin/users/${id}/status`, data)
export const resetPassword = (id, data) => post(`/api/admin/users/${id}/reset-password`, data)
export const listChannels = (params) => get('/api/admin/channels', params)
export const createChannel = (data) => post('/api/admin/channels', data)
export const updateChannel = (id, data) => put(`/api/admin/channels/${id}`, data)
export const deleteChannel = (id) => del(`/api/admin/channels/${id}`)
export const testChannel = (id) => post(`/api/admin/channels/${id}/test`)
export const toggleChannel = (id, data) => post(`/api/admin/channels/${id}/toggle`, data)
export const listCoupons = (params) => get('/api/admin/coupons', params)
export const createCoupon = (data) => post('/api/admin/coupons', data)
export const updateCoupon = (id, data) => put(`/api/admin/coupons/${id}`, data)
export const deleteCoupon = (id) => del(`/api/admin/coupons/${id}`)
export const listModelPrices = (params) => get('/api/admin/model-prices', params)
export const createModelPrice = (data) => post('/api/admin/model-prices', data)
export const deleteModelPrice = (id) => del(`/api/admin/model-prices/${id}`)
export const getChannelStats = () => get('/api/admin/monitor/channels')
export const getRecentErrors = (params) => get('/api/admin/monitor/errors', params)
export const giftBalance = (data) => post('/api/admin/billing/gift', data)
export const refundOrder = (orderNo) => post(`/api/admin/payment/refund/${orderNo}`)
export const getModerationStatus = () => get('/api/admin/moderation/status')
export const toggleModeration = (enabled) => post(`/api/admin/moderation/toggle?enabled=${enabled}`)
